export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_USER_SKILLS = "GET_USER_SKILLS";
export const USER_SKILLS_LOADING = "USER_SKILLS_LOADING";
export const USER_SKILLS_NOT_FOUND = "USER_SKILLS_NOT_FOUND";
export const CLEAR_CURRENT_USER_SKILLS = "CLEAR_CURRENT_USER_SKILLS";

export const GET_REQUIRED_SKILL = "GET_REQUIRED_SKILL";
export const REQUIRED_SKILL_LOADING = "REQUIRED_SKILL_LOADING";
export const REQUIRED_SKILL_NOT_FOUND = "REQUIRED_SKILL_NOT_FOUND";
export const CLEAR_CURRENT_REQUIRED_SKILL = "CLEAR_CURRENT_REQUIRED_SKILL";
export const CLEAR_CURRENT_MATCH = "CLEAR_CURRENT_MATCH";
export const MATCH_LOADING = "MATCH_LOADING";
export const SET_MATCHED_USER = "SET_MATCHED_USER";
